In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
# loading the dataset to a Pandas DataFrame
import pandas as pd
credit_card_data = pd.read_csv("/content/creditcard.csv")
credit_card_data

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [ ]:
# dataset informations
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13954 entries, 0 to 13953
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    13954 non-null  int64
 1   V1      13954 non-null  float64
 2   V2      13954 non-null  float64
 3   V3      13954 non-null  float64
 4   V4      13954 non-null  float64
 5   V5      13954 non-null  float64
 6   V6      13954 non-null  float64
 7   V7      13954 non-null  float64
 8   V8      13954 non-null  float64
 9   V9      13954 non-null  float64
 10  V10     13954 non-null  float64
 11  V11     13954 non-null  float64
 12  V12     13954 non-null  float64
 13  V13     13954 non-null  float64
 14  V14     13954 non-null  float64
 15  V15     13954 non-null  float64
 16  V16     13954 non-null  float64
 17  V17     13954 non-null  float64
 18  V18     13954 non-null  float64
 19  V19     13954 non-null  float64
 20  V20     13954 non-null  float64
 21  V21     13954 non-null  float64
 22  V22     13954 non-null  float64
 23  V23     13954 non-null  float64
 24  V24     13954 non-null  float64
 25  V25     13954 non-null  float64
 26  V26     13954 non-null  float64
 27  V27     13954 non-null  float64
 28  V28     13954 non-null  float64
 29  Amount  13953 non-null  float64
 30  Class   13953 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 3.3 MB

In [ ]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    1
Class     1
dtype: int64

In [ ]:
# distribution of legit transactions & fraudulent transactions
credit_card_data['Class'].value_counts()

Class
0.0    13897
1.0       56
Name: count, dtype: int64

In [ ]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(13897, 31)
(56, 31)

In [ ]:
# statistical measures of the data
legit.Amount.describe()

count    13897.000000
mean        63.773909
std        177.164503
min          0.000000
25%          5.770000
50%         15.900000
75%         52.370000
max       7712.430000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count      56.000000
mean       90.815893
std       310.308450
min         0.000000
25%         1.000000
50%         1.000000
75%         1.025000
max      1809.680000
Name: Amount, dtype: float64

In [ ]:
# compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,10111.481255,-0.217093,0.266252,0.887227,0.276789,-0.107510,0.136745,-0.131462,-0.020385,1.005460,...,0.020758,-0.068686,-0.158230,-0.034834,0.013065,0.117928,0.034349,0.009565,0.002329,63.773909
1.0,12262.107143,-4.727948,4.660436,-9.328536,6.783464,-2.890388,-2.030360,-6.578337,1.028374,-2.981468,...,0.453283,0.116896,0.048132,-0.225526,-0.452514,-0.124184,0.333325,0.793484,-0.046177,90.815893

In [ ]:
legit_sample = legit.sample(n=492)

In [ ]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [ ]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
8517,11433,1.255070,-0.017739,0.612875,-0.043546,-0.537792,-0.471941,-0.429693,-0.057176,1.501593,...,-0.255355,-0.542424,0.055625,-0.005555,0.092787,0.869353,-0.105378,-0.010293,8.00,0.0
2039,1579,-0.039223,1.169977,2.242885,4.045603,0.364060,0.244091,0.739069,-0.412137,-1.495388,...,-0.060894,0.076780,0.031327,0.342435,-0.783978,-0.057340,-0.336967,-0.313952,25.00,0.0
2591,2121,-0.275456,1.016434,0.945444,-0.403299,0.369162,-1.184331,1.045688,-0.404513,0.013437,...,-0.180765,-0.280897,0.178551,0.338902,-1.249753,-0.287541,0.148848,0.079591,9.99,0.0
9010,12521,1.045399,0.020179,0.879342,1.406794,-0.695494,-0.587486,-0.224606,-0.172379,1.620989,...,0.031410,0.193025,-0.143858,0.340647,0.473738,-0.343877,-0.000043,0.039508,90.71,0.0
10710,18129,-0.428723,1.133529,1.704026,0.177730,0.021682,-0.857459,0.609343,-0.148267,0.883861,...,-0.374999,-0.779541,-0.001180,0.300544,-0.213110,0.032683,0.237200,0.115248,5.35,0.0

In [ ]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
11880,20451,-15.819179,8.775997,-22.804686,11.864868,-9.092361,-2.386893,-16.560368,0.948349,-6.310658,...,-2.350634,1.036362,1.136051,-1.043414,-0.108923,0.657437,2.136424,-1.411945,1.0,1.0
12070,20931,-16.367923,9.223692,-23.270631,11.844777,-9.462037,-2.450444,-16.925152,1.384208,-6.287736,...,-2.343674,1.004602,1.188212,-1.047184,-0.035573,0.664900,2.122796,-1.416741,1.0,1.0
12108,21046,-16.917468,9.669900,-23.736443,11.824990,-9.830548,-2.514829,-17.290657,1.820408,-6.264903,...,-2.336111,0.972755,1.241866,-1.051086,0.038009,0.672317,2.108471,-1.421243,1.0,1.0
12261,21419,-17.467710,10.114816,-24.202142,11.805469,-10.198046,-2.579938,-17.656788,2.256902,-6.242149,...,-2.328024,0.940830,1.296817,-1.055104,0.111792,0.679695,2.093541,-1.425491,1.0,1.0
12369,21662,-18.018561,10.558600,-24.667741,11.786180,-10.564657,-2.645681,-18.023468,2.693655,-6.219464,...,-2.319479,0.908839,1.352904,-1.059222,0.185751,0.687037,2.078081,-1.429517,1.0,1.0

In [ ]:
new_dataset['Class'].value_counts()

Class
0.0    492
1.0     56
Name: count, dtype: int64

In [ ]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,10543.886179,-0.294634,0.266081,0.897694,0.262314,-0.026744,0.031325,-0.220560,-0.081869,1.071481,...,0.002425,-0.056630,-0.189672,-0.042002,0.030647,0.117446,0.032044,0.019731,-0.021745,51.810102
1.0,12262.107143,-4.727948,4.660436,-9.328536,6.783464,-2.890388,-2.030360,-6.578337,1.028374,-2.981468,...,0.453283,0.116896,0.048132,-0.225526,-0.452514,-0.124184,0.333325,0.793484,-0.046177,90.815893

In [ ]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']
print(X)

        Time         V1         V2         V3         V4         V5        V6  \
8517   11433   1.255070  -0.017739   0.612875  -0.043546  -0.537792 -0.471941
2039    1579  -0.039223   1.169977   2.242885   4.045603   0.364060  0.244091
2591    2121  -0.275456   1.016434   0.945444  -0.403299   0.369162 -1.184331
9010   12521   1.045399   0.020179   0.879342   1.406794  -0.695494 -0.587486
10710  18129  -0.428723   1.133529   1.704026   0.177730   0.021682 -0.857459
...      ...        ...        ...        ...        ...        ...       ...
11880  20451 -15.819179   8.775997 -22.804686  11.864868  -9.092361 -2.386893
12070  20931 -16.367923   9.223692 -23.270631  11.844777  -9.462037 -2.450444
12108  21046 -16.917468   9.669900 -23.736443  11.824990  -9.830548 -2.514829
12261  21419 -17.467710  10.114816 -24.202142  11.805469 -10.198046 -2.579938
12369  21662 -18.018561  10.558600 -24.667741  11.786180 -10.564657 -2.645681

              V7        V8        V9  ...       V20       V21       V22  \
8517   -0.429693 -0.057176  1.501593  ... -0.100132 -0.255355 -0.542424
2039    0.739069 -0.412137 -1.495388  ...  0.240024 -0.060894  0.076780
2591    1.045688 -0.404513  0.013437  ...  0.034762 -0.180765 -0.280897
9010   -0.224606 -0.172379  1.620989  ... -0.006082  0.031410  0.193025
10710   0.609343 -0.148267  0.883861  ...  0.067826 -0.374999 -0.779541
...          ...       ...       ...  ...       ...       ...       ...
11880 -16.560368  0.948349 -6.310658  ...  0.992279 -2.350634  1.036362
12070 -16.925152  1.384208 -6.287736  ...  0.993585 -2.343674  1.004602
12108 -17.290657  1.820408 -6.264903  ...  0.996745 -2.336111  0.972755
12261 -17.656788  2.256902 -6.242149  ...  1.001519 -2.328024  0.940830
12369 -18.023468  2.693655 -6.219464  ...  1.007703 -2.319479  0.908839

            V23       V24       V25       V26       V27       V28  Amount
8517   0.055625 -0.005555  0.092787  0.869353 -0.105378 -0.010293    8.00
2039   0.031327  0.342435 -0.783978 -0.057340 -0.336967 -0.313952   25.00
2591   0.178551  0.338902 -1.249753 -0.287541  0.148848  0.079591    9.99
9010  -0.143858  0.340647  0.473738 -0.343877 -0.000043  0.039508   90.71
10710 -0.001180  0.300544 -0.213110  0.032683  0.237200  0.115248    5.35
...         ...       ...       ...       ...       ...       ...     ...
11880  1.136051 -1.043414 -0.108923  0.657437  2.136424 -1.411945    1.00
12070  1.188212 -1.047184 -0.035573  0.664900  2.122796 -1.416741    1.00
12108  1.241866 -1.051086  0.038009  0.672317  2.108471 -1.421243    1.00
12261  1.296817 -1.055104  0.111792  0.679695  2.093541 -1.425491    1.00
12369  1.352904 -1.059222  0.185751  0.687037  2.078081 -1.429517    1.00

[548 rows x 30 columns]

In [ ]:
print(Y)

8517     0.0
2039     0.0
2591     0.0
9010     0.0
10710    0.0
        ...
11880    1.0
12070    1.0
12108    1.0
12261    1.0
12369    1.0
Name: Class, Length: 548, dtype: float64

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

In [ ]:
 model = LogisticRegression()

In [ ]:
# training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [ ]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.9863013698630136